### ISSUE TITLE
[Feature Request]Support Helm Chart

### ISSUE THREAD

**Issue by pomcho555** [dtaniwaki/cron-hpa#2]
I am looking for HPA having a cron like feature. I think this CRD has more features than the others. This product meet our needs. So, it's cool for us to support Helm Chart to manage the manifests. 

FYI: the similar product has already supported [the feature](https://github.com/AliyunContainerService/kubernetes-cronhpa-controller/tree/master/chart/kubernetes-cronhpa-controller).

**Comment by dtaniwaki** [comment]
Thank you for researching this controller. I'll add a Helm chart soon!

**Comment by dtaniwaki** [comment]
@pomcho555 
https://github.com/dtaniwaki/cron-hpa/tree/main/chart/cron-hpa
I added a Helm chart of basic resources. Please try it and tell me any feedback.

**Comment by pomcho555** [comment]
Thank you for your quick implementation. I'll try it.
